In [1]:
import csv
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

C:\Users\wwwsa\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [9]:

with open("bbc-text.csv", 'r') as csvfile:
    print(f"First line (header) looks like this:\n\n{csvfile.readline()}")
    print(f"Each data point looks like this:\n\n{csvfile.readline()}")   

First line (header) looks like this:

category,text

Each data point looks like this:

tech,tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room  the way people watch tv will be radically different in five years  time.  that is according to an expert panel which gathered at the annual consumer electronics show in las vegas to discuss how these new technologies will impact one of our favourite pastimes. with the us leading the trend  programmes and other content will be delivered to viewers via home networks  through cable  satellite  telecoms companies  and broadband service providers to front rooms and portable devices.  one of the most talked-about technologies of ces has been digital and personal video recorders (dvr and pvr). these set-top boxes  like the us s tivo and the uk s sky+ system  allow people to record  store  play  pause and forward wind tv programmes when they want.  essentially

In [21]:
print(type(csvfile))

<class '_io.TextIOWrapper'>


In [31]:
# function to remove stop words
def remove_stopword(sentence):
    
    #list of stopwords
    stopwords = ["a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves" ]
    # sentence converted to lowercase
    sentence = sentence.lower()
    
    #filtering stopwords out of the sentences
    words = sentence.split()
    output = [word for word in words if word not in stopwords]
    sentence = ' '.join(output)
    
    return sentence


In [32]:
stopwords=["a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves" ]
    
print(type(stopwords))

<class 'list'>


In [33]:
print(len(stopwords))

153


In [35]:
remove_stopword("agriculture is the primary occupation of the tribe here")

'agriculture primary occupation tribe'

In [40]:
#Parsing data in Python involves breaking down a given text
#or file into smaller parts that can be easily analyzed and manipulated.
def parse_data_from_file(filename):
    #variable initialization
    #two empty strings are created
    sentences= []
    labels=[]
    #The with statement opens the CSV file specified by filename in read mode ('r')
    # and assigns the file object to the csvfile variable.
    #The with statement ensures proper file closing even if exceptions occur.
    with open(filename,'r') as csvfile:
        reader = csv.reader(csvfile,delimiter=',')
        #skip header
        next(reader,None)
        
        for row in reader:
            labels.append(remove_stopword(row[0]))
            sentences.append(remove_stopword(row[1]))
    
    return sentences,labels
        

In [43]:
sentences,labels = parse_data_from_file("bbc-text.csv")

In [44]:
len(sentences)

2225

In [45]:
len(labels)

2225

In [53]:
print(type(sentences))
print(type(labels))


<class 'list'>
<class 'list'>


In [58]:
#printing the first two items of the list
print(sentences[:2])

['tv future hands viewers home theatre systems plasma high-definition tvs digital video recorders moving living room way people watch tv will radically different five years time. according expert panel gathered annual consumer electronics show las vegas discuss new technologies will impact one favourite pastimes. us leading trend programmes content will delivered viewers via home networks cable satellite telecoms companies broadband service providers front rooms portable devices. one talked-about technologies ces digital personal video recorders (dvr pvr). set-top boxes like us s tivo uk s sky+ system allow people record store play pause forward wind tv programmes want. essentially technology allows much personalised tv. also built-in high-definition tv sets big business japan us slower take off europe lack high-definition programming. not can people forward wind adverts can also forget abiding network channel schedules putting together a-la-carte entertainment. us networks cable satel

In [55]:
print(labels[:10])

['tech', 'business', 'sport', 'sport', 'entertainment', 'politics', 'politics', 'sport', 'sport', 'entertainment']


In [62]:
def fit_tokenizer(sentences):
    
    # instantiate the Tokenizer class by passing in the oov_token argument
    tokenizer = Tokenizer(oov_token="<OOV>")
    #fit on the sentences
    tokenizer.fit_on_texts(sentences)
    
    return tokenizer

In [63]:
tokenizer = fit_tokenizer(sentences)
word_index = tokenizer.word_index

In [67]:
print(type(tokenizer))


<class 'keras.preprocessing.text.Tokenizer'>


In [68]:
print(type(word_index))
print(len(word_index))

<class 'dict'>
29714


In [70]:
print("OOV TOKEN YES" if "<OOV>" in word_index else "OOV TOKEN NO")

OOV TOKEN YES


In [73]:
#printing the first 10 key value pairs of the word index dictionary
first_10_pairs = list(word_index.items())[:10]

for key, value in first_10_pairs:
    print(f"{key}: {value}")

<OOV>: 1
s: 2
said: 3
will: 4
not: 5
mr: 6
year: 7
also: 8
people: 9
new: 10


In [103]:
def get_padded_sequences(tokenizer,sentences):
    
    # tokenizer instance containing the word-index dictionary
    #sentences: list of sentences to tokenize and pad
    
    #convert sentence to sequences
    sequences = tokenizer.texts_to_sequences(sentences)
    
    #pad the sequences using the post padding strategy
    padded_sequences = pad_sequences(sequences, padding='post')
    
    return padded_sequences, sequences

In [107]:
padded_sequences,type2 = get_padded_sequences(tokenizer,sentences)
type2[:1]

[[96,
  176,
  1157,
  1220,
  54,
  1122,
  742,
  5211,
  85,
  1074,
  4267,
  147,
  184,
  4127,
  1344,
  1311,
  1595,
  47,
  9,
  949,
  96,
  4,
  6516,
  329,
  92,
  23,
  17,
  140,
  3128,
  1330,
  2519,
  576,
  419,
  1277,
  72,
  2963,
  3046,
  1755,
  10,
  894,
  4,
  755,
  12,
  954,
  19513,
  11,
  656,
  1578,
  1053,
  414,
  4,
  1999,
  1220,
  778,
  54,
  502,
  1497,
  2114,
  1652,
  135,
  333,
  123,
  2744,
  817,
  5212,
  1088,
  609,
  12,
  4413,
  4128,
  894,
  2580,
  147,
  351,
  184,
  4127,
  8812,
  5798,
  44,
  73,
  3218,
  31,
  11,
  2,
  5473,
  22,
  2,
  1397,
  145,
  454,
  9,
  138,
  1398,
  82,
  4598,
  488,
  5213,
  96,
  1053,
  87,
  6517,
  83,
  2115,
  63,
  8813,
  96,
  8,
  1123,
  634,
  85,
  1074,
  96,
  1970,
  148,
  159,
  420,
  11,
  2879,
  46,
  56,
  149,
  1221,
  85,
  1074,
  4414,
  5,
  13,
  9,
  488,
  5213,
  3129,
  13,
  8,
  2693,
  6967,
  412,
  1097,
  8814,
  1376,
  616,
  1469,
  2079,

In [77]:
print(type(padded_sequences))

<class 'numpy.ndarray'>


In [78]:
print(padded_sequences[:10])

[[  96  176 1157 ...    0    0    0]
 [1619  610  252 ...    0    0    0]
 [4997 6975 3852 ...    0    0    0]
 ...
 [1883  715 1281 ...    0    0    0]
 [2397 1205  309 ...    0    0    0]
 [  14  238 2642 ...    0    0    0]]


In [79]:
print(padded_sequences.shape)

(2225, 2438)


In [83]:
# first padded sequence
print(padded_sequences[0])

[  96  176 1157 ...    0    0    0]


In [91]:
def tokenize_labels(labels):
    #labels: list of strings
    
    #instantiate the tokenizer
    label_tokenizer = Tokenizer()
    
    #fit the tokenizer to the labels
    label_tokenizer.fit_on_texts(labels)
    
    #save the word index
    label_word_index = label_tokenizer.word_index
    
    #save the sequences
    label_sequences  = label_tokenizer.texts_to_sequences(labels)
    
    return label_sequences, label_word_index

In [92]:
label_sequences,label_word_index = tokenize_labels(labels)

In [94]:
print(type(label_sequences))
print(len(label_sequences))

<class 'list'>
2225


In [95]:
print(label_word_index)

{'sport': 1, 'business': 2, 'politics': 3, 'tech': 4, 'entertainment': 5}


In [96]:
print(label_sequences[:10])

[[4], [2], [1], [1], [5], [3], [3], [1], [1], [5]]
